"use client";
// import {  ThemeProvider } from '@mui/material/styles';
import "./globals.css";
import { Inter } from "next/font/google";
import customizeTheme from "@/theme/customizeTheme";
import { Button, CssBaseline, Paper, Typography } from "@mui/material";
import { useState } from "react";
import { ThemeProvider, useTheme, createTheme } from "@mui/material/styles";
import { amber, deepOrange, grey } from "@mui/material/colors";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Personal Blog",
  description: "Generated by create next app",
};

const getDesignTokens = (mode) => ({
  palette: {
    mode,
    primary: {
      ...amber,
      ...(mode === "dark" && {
        main: amber[300],
      }),
    },
    ...(mode === "dark" && {
      background: {
        default: deepOrange[900],
        paper: deepOrange[900],
      },
    }),
    // ...(mode === 'light'
    // ? {
    //     primary: {
    //       main:grey[900]
    //     },
    //     secondary: {
    //       main:grey[800]
    //     },
    //     custom:{
    //       main:"#94C9A9"
    //     }
    //   }
    // : {
    //     primary: {
    //       main:'#C6ECAE'
    //     },
    //     secondary: {
    //       main:grey[500]
    //     },
    //   }),
    text: {
      ...(mode === "light"
        ? {
            primary: grey[900],
            secondary: grey[800],
          }
        : {
            primary: "#C6ECAE",
            secondary: grey[500],
          }),
    },
  },
});

export default function RootLayout({ children }) {
  const [theme, setTheme] = useState(false);
  const useThemeColor = useTheme();

  const darkModeTheme = createTheme(getDesignTokens(theme ? "dark" : "light"));

  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider theme={darkModeTheme}>
          <CssBaseline />
          <>
            <button onClick={() => setTheme(!theme)}>change </button>
            <Typography variant="h6">{theme ? "dark" :  "white"}</Typography>
            <Typography sx={{ color: "custom" }}>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Debitis,
              eos?
            </Typography>
            <Button>Button</Button>
            {children}
          </>
        </ThemeProvider>
      </body>
    </html>
  );
}
